apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecatalog-api-pvc
  namespace: elsewedy-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
